plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

remote_theme: piharpi/jekyll-klise

# Site settings
title: Klise Theme
description: >-
  He's writing in Bahasa about web technology and experience...
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png
repo: https://github.com/piharpi/jekyll-klise
mode: dark

# Profile settings
author:
  name: Jekyll Klisé
  bio: >-
    The minimalist Jekyll theme...
  username: username
  github: github_username
  email: your-email@email.com
  avatar: /assets/img/avatar.jpg

# URL settings
url: "https://your-username.github.io" # 🔥 Change this
baseurl: ""
permalink: /:title/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

remote_theme: piharpi/jekyll-klise
