plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

remote_theme: piharpi/jekyll-klise

# Site settings
title: Klise Theme
description: >-
  Undergraduate Student | Computational Mathematics | Kathmandu University (KU)
lang: en-US
timezone: Asia/Kathmandu
image: assets/img/peter.jpeg
repo: https://github.com/piharpi/jekyll-klise
mode: light

# Profile settings
author:
  name: Sashuv Kafle
  bio: >-
    Undergraduate Student | Computational Mathematics | Kathmandu University (KU)
  username: sashuv
  github: Sashuv
  email: kafle.sashuv@gmail.com
  avatar: /assets/img/profilepic.jpeg

# URL settings
url: "https://sashuv.github.io" 
baseurl: ""
permalink: /:title/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

remote_theme: piharpi/jekyll-klise

collections:
  projects:
    output: true
